3Squared/ForgeUI-3

.changeset/six-zebras-deny.md
apps/docs/src/pages/overlay/Modal.vue
packages/ui/src/Bootstrap_PT.ts
packages/ui/src/components/ForgeModal.vue
packages/ui/tests/component/dialog/dialog.cy.ts

- Fix issue where PrimeVue slots weren't rendering.
- Fix styling issue where close and maximise icons were too big.
- Update tag in generated code on Modal's documentation page.

Forge modal enhancements and fixes

---

.changeset/sweet-mangos-thank.md
packages/ui/src/passthroughs/Image.pt.ts
packages/ui/src/styles/components/_file-uploader.scss

- Fix issue where large images would appear off the screen.
- Fix issue where the toolbar would appear under the image.

Forge file uploader - Fix issues previewing large images.

---

.changeset/purple-peas-drop.md
apps/docs/src/pages/forms/inputs/FormField.vue
packages/ui/src/components/ForgeFormField.vue
packages/ui/tests/component/form-field/form-field.cy.ts

Add prop to position the label of the ForgeFormField above or to the left of the input

---

.changeset/tender-emus-sleep.md
packages/ui/src/styles/utilities/_variables.scss

Added width classes:
- 5: 5%,
- 10: 10%,
- 20: 20%,
- 25: 25%,
- 30: 30%,
- 40: 40%,
- 50: 50%,
- 60: 60%,
- 75: 75%,
- 80: 80%,
- 90: 90%,
- 100: 100%,

feat(add extra width classes)

---

.changeset/good-pumpkins-smell.md
packages/ui/tests/component/fieldset/fieldset.cy.ts

Stop cypress test from timing out

Fix fieldset test

---

.changeset/olive-eels-join.md
apps/docs/src/pages/forms/dropdowns/MultiselectPreview.vue
package-lock.json
packages/ui/package.json
packages/ui/src/components/ForgeMultiSelectPreview.vue

Multiselect changes:
- Remove chip default from multiselect preview
- Improve to multiselect documentation

Multiselect changes

---

.changeset/green-countries-judge.md
apps/docs/src/composables/playgroundOptions.ts
apps/docs/src/pages/forms/inputs/FormField.vue
apps/docs/src/pages/forms/inputs/examples/FormExamples.vue
apps/docs/typed-router.d.ts
package-lock.json
packages/ui/src/components/ForgeFormField.vue
packages/ui/src/components/ForgeMultiSelectPreview.vue
packages/ui/src/types/forge-types.ts

Add multiselect-preview into ForgeFormField so that validation can be easily implemented.

Add multiselect preview to forge form field

---

.changeset/unlucky-socks-look.md
packages/ui/src/passthroughs/Table.pt.ts
packages/ui/src/styles/components/_table.scss

Improve paginator:
- Remove if there are no initial values
- Disable if the buttons don't do anything

Add pagination improvements

---

.changeset/hip-kiwis-camp.md
apps/docs/src/pages/buttons/ActionButton.vue
apps/docs/src/pages/forms/Form.vue
apps/docs/src/pages/forms/dropdowns/MultiselectPreview.vue

Update docs to follow naming conventions (so I can remove issues)

Doc updates

---

.changeset/poor-peas-unite.md
packages/ui/src/components/ForgeCheckbox.vue
packages/ui/src/passthroughs/Checkbox.pt.ts

fix checkbox readonly styling and functionality

---

.changeset/icy-frogs-cover.md
packages/ui/src/components/table/ForgeFilterHeader.vue

Trim text filter value in table

Trim text filter value

---

.changeset/light-spies-lie.md
apps/docs/src/pages/examples/components/ExampleModal.vue
apps/docs/src/pages/overlay/Modal.vue
apps/docs/typed-router.d.ts
packages/ui/src/components/ForgeModal.vue

Add customisable error

---

.changeset/proud-rats-tap.md
package-lock.json
packages/ui/src/components/ForgePanel.vue
packages/ui/src/passthroughs/Panel.pt.ts
packages/ui/tests/component/table/table.cy.ts

Change the way slots are passed into the panel
Fix table date test

Fix panel slots

---

.changeset/famous-mammals-walk.md
apps/docs/src/pages/data/Table.vue
packages/ui/src/components/table/ForgePaginationHeader.vue
packages/ui/src/components/table/ForgeTable.vue
packages/ui/tests/component/table/table.cy.ts

Alow forge table to have a different page size default, from the current 10

Add perPage prop to ForgeTable

---

.changeset/tall-dragons-give.md
apps/docs/src/pages/examples/data/exampleTreeNodes.ts
apps/docs/src/pages/forms/dropdowns/Dropdown.vue
apps/docs/src/pages/forms/dropdowns/TreeSelect.vue
packages/ui/src/passthroughs/Dropdown.pt.ts
packages/ui/src/passthroughs/TreeSelect.pt.ts

Add css fixes to dropdowns - stop resizing if content is too long

Add css fixes

---

.changeset/hip-corners-dream.md
packages/ui/src/components/file-uploader/components/UploadStatus.vue

Set forge loader to be inline for file uploader

Set file uploader to be inline

---

.changeset/all-candies-travel.md
apps/docs/src/pages/data/TreeTable.vue
packages/ui/src/components/ForgeTreeTable.vue

Introduce ForgeTreeTable EmptyMessage slot
* Update existing documentation spelling mistake

Introduce ForgeTreeTable EmptyMessage slot

---

.changeset/stale-roses-know.md
packages/ui/src/passthroughs/Column.pt.ts

Fix colspan and rowspan prop check on Table passthrough

Fix table passthrough bug

---

.changeset/smooth-chefs-retire.md
apps/docs/src/pages/examples/components/ExampleTableGroup.vue
package-lock.json
packages/ui/package.json
packages/ui/src/components/table/ForgeTable.vue
packages/ui/src/passthroughs/Column.pt.ts
packages/ui/src/passthroughs/Table.pt.ts

Fix table sort badge and rowGroupHeader styling

Fix table styling

---

.changeset/cyan-months-hammer.md
package-lock.json
packages/ui/package.json
packages/ui/src/styles/main.scss
packages/ui/src/styles/utilities/_utilities.scss

Move flex class to export it properly

Move flex class

---

.changeset/long-hats-laugh.md
package-lock.json
packages/ui/src/components/ForgePickList.vue
packages/ui/src/passthroughs/PickList.pt.ts

Center buttons vertically in pick list component

Make buttons centred

---

.changeset/solid-rivers-brush.md
packages/ui/src/components/table/ForgeFilterHeader.vue
packages/ui/src/components/table/ForgeTable.vue
packages/ui/src/passthroughs/Table.pt.ts

Add styling to row group header cell
Remove filter close button when input is empty

Add styling to group header

---

.changeset/itchy-pugs-knock.md
packages/ui/src/components/ForgePickList.vue

Change how the 2 sets of lists are used and model populated within the picklist, using new arrays, and splifce methods to mutate the model

Update how the data is used and populated for the picklist values

---

package-lock.json

Fix release, by updating package lock with required dependencies

Update Package lock file with dependencies
